# Generated by Django 5.1 on 2025-01-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='exercices',
            field=models.ManyToManyField(related_name='workouts', through='workouts.WorkoutExercise', to='workouts.exercise'),
        ),
        migrations.DeleteModel(
            name='UserWorkout',
        ),
    ]
