# Generated by Django 5.1 on 2025-01-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_height_alter_customuser_weight'),
        ('workouts', '0002_workout_exercices_delete_userworkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='workouts',
            field=models.ManyToManyField(related_name='users', to='workouts.workout'),
        ),
    ]
