# Generated by Django 5.1 on 2025-01-17 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_profile_picture_alter_customuser_gender'),
        ('workouts', '0003_workout_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='workouts',
        ),
        migrations.AddField(
            model_name='customuser',
            name='workouts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.workout'),
        ),
    ]
