# Generated by Django 5.1 on 2025-01-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_workouts_customuser_workouts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='workouts',
        ),
    ]
